image: node:18.17.0

pipelines:
  pull-requests:
    hotfix/*:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build and push tot container registry
          deployment: staging
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
            - docker login $DOCKER_DOMAIN -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - COMMIT_HASH=$BITBUCKET_COMMIT
            - docker build -t $DOCKER_DOMAIN/tilburg-woo-ui-test:staging .
            - docker push $DOCKER_DOMAIN/tilburg-woo-ui-test:staging
          services:
            - docker
  branches:
    develop:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build and push tot container registry
          deployment: develop
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
            - docker login $DOCKER_DOMAIN -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - COMMIT_HASH=$BITBUCKET_COMMIT
            - docker build -t $DOCKER_DOMAIN/tilburg-woo-ui-test:dev .
            - docker push $DOCKER_DOMAIN/tilburg-woo-ui-test:dev
          services:
            - docker
    release/*:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build and push tot container registry
          deployment: staging
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
            - docker login $DOCKER_DOMAIN -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - COMMIT_HASH=$BITBUCKET_COMMIT
            - docker build -t $DOCKER_DOMAIN/tilburg-woo-ui-test:staging .
            - docker push $DOCKER_DOMAIN/tilburg-woo-ui-test:staging
          services:
            - docker
  custom: # Pipelines that are triggered manually
    production:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build and push tot container registry
          deployment: production
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
            - docker login $DOCKER_DOMAIN -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - COMMIT_HASH=$BITBUCKET_COMMIT
            - docker build -t $DOCKER_DOMAIN/tilburg-woo-ui-test:prod .
            - docker push $DOCKER_DOMAIN/tilburg-woo-ui-test:prod
          services:
              - docker
definitions:
  caches:
    nodecustom: ./node_modules
    yarn: /usr/local/share/.cache/yarn
