image: node:18.17.0

pipelines:
  pull-requests:
    hotfix/*:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build
          deployment: staging
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
          artifacts:
            - public_html/**
      - step:
          name: Deploy to staging
          image: acatonl/php-deployer-pipeline:8.1
          script:
            - deployer.phar deploy staging
  branches:
    develop:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build
          deployment: develop
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
          artifacts:
            - public_html/**
      - step:
          name: Deploy to development
          image: acatonl/php-deployer-pipeline:8.1
          script:
            - deployer.phar deploy develop
    release/*:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build
          deployment: staging
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
          artifacts:
            - public_html/**
      - step:
          name: Deploy to staging
          image: acatonl/php-deployer-pipeline:8.1
          script:
            - deployer.phar deploy staging
  custom: # Pipelines that are triggered manually
    azure-test:
      - step:
          name: Install
          caches:
            - nodecustom
            - yarn
          script:
            - unset CI
            - yarn set version 4.1.1
            - yarn
          artifacts:
            - node_modules/**
      - step:
          name: Build and push tot container registry
          deployment: develop
          script:
            - unset CI
            - env | awk -F"DOTENV_" '/^DOTENV_/ {print $2}' >> .env
            - yarn set version 4.1.1
            - yarn build:web
            - docker login $DOCKER_DOMAIN -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - COMMIT_HASH=$BITBUCKET_COMMIT
            - docker build -t $DOCKER_DOMAIN/tilburg-woo-ui-test:$COMMIT_HASH .
            - docker push $DOCKER_DOMAIN/tilburg-woo-ui-test:$COMMIT_HASH
          services:
              - docker
definitions:
  caches:
    nodecustom: ./node_modules
    yarn: /usr/local/share/.cache/yarn
