apiVersion: v2
name: tilburg-woo-ui
description: A Helm chart for Tilburg WOO UI application
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/ConductionNL/tilburg-woo-ui
sources:
  - https://github.com/ConductionNL/tilburg-woo-ui
maintainers:
  - name: ConductionNL
    url: https://github.com/ConductionNL
keywords:
  - woo
  - tilburg
  - ui
  - frontend
  - react 